# Telegram Bot Configuration
# Get your bot token from @BotFather on Telegram
telegram:
  botToken: 'YOUR_BOT_TOKEN_HERE'
  chatId: -1001234567890  # Your Telegram chat/channel ID
  threadId: 1  # Thread ID in your chat/channel (use 1 for main thread)

# Database Configuration
database:
  path: '/app/data/ads.db'  # Path to SQLite database file

# Scraping Configuration
scraper:
  url: 'https://www.kleinanzeigen.de/s-zu-verschenken/berlin/k0c192l1000r35'  # Default URL (not used when filters are defined)
  intervalMinutes: 30  # How often to check for new ads (in minutes)

# Search Filters
# Each filter will be processed independently and send ads to different Telegram threads
filters:
  - name: 'Free Items - Furniture'
    url: 'https://www.kleinanzeigen.de/s-zu-verschenken/berlin/moebel/k0c192l1000r35'
    telegramChatId: '-1001234567890'  # Chat ID as string
    telegramThreadId: 3  # Thread for this filter

  - name: 'Furniture for Sale'
    url: 'https://www.kleinanzeigen.de/s-wohnzimmer/berlin/preis::500/moebel/k0c88l1000r35'
    telegramChatId: '-1001234567890'
    telegramThreadId: 2

  - name: 'Electronics Free'
    url: 'https://www.kleinanzeigen.de/s-zu-verschenken/berlin/elektronik/k0c192l1000r35'
    telegramChatId: '-1001234567890'
    telegramThreadId: 417

  - name: 'Electronics for Sale'
    url: 'https://www.kleinanzeigen.de/s-elektronik/berlin/preis::200/computer-konsolen/k0c74l1000'
    telegramChatId: '-1001234567890'
    telegramThreadId: 419

  - name: 'Books Free'
    url: 'https://www.kleinanzeigen.de/s-zu-verschenken/berlin/buecher/k0c192l1000r35'
    telegramChatId: '-1001234567890'
    telegramThreadId: 561

  - name: 'Books for Sale'
    url: 'https://www.kleinanzeigen.de/s-buecher/berlin/preis::50/buecher/k0c75l1000r35'
    telegramChatId: '-1001234567890'
    telegramThreadId: 558 